### ISSUE TITLE
Code does not pass typechecker

### ISSUE THREAD

**Issue by jwatzman** [mcuadros/pimple-hack#1]
Hey! I'm an engineer working on Hack, really awesome to see folks using it! Just saw your project and was playing around a bit with it.

Although it works at runtime, Pimple doesn't actually pass the static typechecker. Many of the nice properties of Hack are enforced statically by the typechecker, which it looks like you aren't running, thus missing out on a lot of the benefits of Hack -- the fast checks of type safety.

You should take a look at [our docs on getting started with Hack](http://docs.hhvm.com/manual/en/install.hack.bootstrapping.php). The short version is that you need to create an empty file called `.hhconfig` in the root of your project, and then run `hh_client` (which should come preinstalled in the HHVM packages, or be in `hphp/hack/bin` if you built HHVM from source).

You'll then get a type error in one of your unit tests:

```
/data/users/jwatzman/pimple-hack/tests/Pimple/Tests/PimpleTest.php:43:9,24: This is not a container, this is an object of type Pimple
  /data/users/jwatzman/pimple-hack/tests/Pimple/Tests/PimpleTest.php:42:19,30: You might want to check this out
```

This is because [Hack does not support `ArrayAccess`](http://docs.hhvm.com/manual/en/hack.unsupported.php), which it looks like Pimple relies heavily upon. Again, it may happen to work at runtime right now, but since it doesn't pass the typechecker, there's no guarantees that it might stop working at some random point in the future.

There are a couple of things you can do to fix this. The best is to rethink Pimple to not require `ArrayAccess` -- but I'm not sure how much of this you wan to do as part of the Hack conversion :) But without doing this, any calling code can't be valid Hack without directly calling `offsetGet` or `offsetSet` -- which is the other two ways to fix your test: directly call those functions, or move it out of Hack entirely.

Let me know if any of this is unclear. Sorry you missed this in the docs -- I'm planning on making it harder to make this mistake in the future!

**Comment by mcuadros** [comment]
Hi @jwatzman 

Thanks for take a look, but this is not the final work, the final work can be found at this PR https://github.com/fabpot/Pimple/pull/122

I will merge it to this repository, to keep the record. This code pass the typechecker, at least some weeks ago.

Regards

**Comment by jwatzman** [comment]
Awesome, didn't realize that, thanks!
